title: Jeremie DIATTA
logo: /img/IngeTalent.png
description: "Portfolio | Mechanical Engineer | CAD & Automation"
show_downloads: false
theme: jekyll-theme-cayman
lang: en
google_analytics: UA-XXXXXXXXX-X # si tu veux tracker les visites
social_links:
  linkedin: https://www.linkedin.com/in/jeremie-diatta
  github: https://github.com/jeremiediatta
  email: ingetalent@gmail.com
