title: "Jeremie DIATTA - Mechanical Engineer"
logo: img/IngeTalent.png
description: "Portfolio - Mechanical Design, FEA, Automation, CAD Macros"
show_downloads: false
theme: jekyll-theme-cayman
lang: en
author: Jeremie Diatta
email: contact@ingetalent.com
linkedin: https://www.linkedin.com/in/jeremie-diatta
github: https://github.com/JeremieDiatta
