title: "Jeremie DIATTA"
logo: "/img/IngeTalent.png"
description: "Portfolio | Mechanical Engineer | CAD, FEA, Automation"
lang: en
theme: jekyll-theme-minimal

# Options
show_downloads: false

# Personnalisation
author: "Jeremie DIATTA"
email: "contact@ingetalent.com"
github_username: "JeremieDiatta"
linkedin_username: "jeremie-diatta"

# SEO & Analytics
google_analytics: UA-XXXXXXXXX-X   # <-- (si tu veux suivre ton trafic, sinon tu supprimes)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation (menu)
nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projects
  - name: "Blog"
    link: /blog
  - name: "About"
    link: /about
  - name: "Contact"
    link: /contact
